### PR TITLE
Updates to website to add the function reference

### PR DESCRIPTION
**Pull request by j-ales**
This commit contains a few changes that add functions references back to website:
1) Function references output as markdown files in the doc/* folder
2) Changes to enable markdown links in function references to work: permalink style set to have html endings inside of directory
3) changes to support testing on a forked project page.  On forked project page baseurl  is the project name and if this isn't set right relative links  don't work.  This caused the .css stylesheets not to be found and other problems with relative links  adding {{ site.baseurl }} before relative links adds the appropriate project name to links. 
4) Changes to formatting styles.css to give the help files a bit more room on the page
5) adding a jekyll plugin to remove titles from headings. Otherwise the headings are made the titles of the pages and they show up as doubled in the help markdowns. 
6) moved footer to be under mfile help.

### CODE REVIEW

**Comment by j-ales** [comment]
Test site running at: https://aleslab.github.io/psychtoolbox-3.github.com/
I think this could go live and remove the need for the docs.psychtoolbox.org server.

**Comment by DavidBrainard** [comment]
Merged.  Now, I will see if I can point psychtoolbox.org at this.  More soon.

**Comment by DavidBrainard** [comment]
Well, let me take that back.  First we have to have a URL so that this stuff shows up on github.io, then I can point at it.

I don't know how to do that, but if someone can provide instructions.  The site appears to be in its own repo, but I thought the standard was to have a specially named branch of the main repo.

In any case, let me know what to do and I'll try to do it.

**Comment by j-ales** [comment]
It looks live now to me

**Comment by j-ales** [comment]
I think the confusion comes from the new ways github allows to organize pages. A special branch on a project is one way. But not how this is setup. See the following link for explanation. The upshot is any push to the master becomes live after the system renders the updated site. 

https://help.github.com/articles/user-organization-and-project-pages/

**Comment by DavidBrainard** [comment]
Got it.  We will disable the server that was housing the autogenerated docs, and see if anything breaks.

**Comment by dcnieho** [comment]
The "function reference" stuff on the main PTB site works beautifully. Is this the result of your work Justin? Great job man!

Cheers,
Dee

**Pull request merged**
